// doocs-md-new/src/components/CustomUploadForm.tsx
import { useEffect, useRef } from 'react'
import { useAppStore } from '@/stores'
import CodeMirror from 'codemirror'
import { Button } from '@/components/ui/button'
import { toast } from 'sonner'

export function CustomUploadForm() {
  const { formCustomConfig, setFormCustomConfig, isDark } = useAppStore()
  const textareaRef = useRef<HTMLTextAreaElement>(null)
  const editorRef = useRef<CodeMirror.EditorFromTextArea | null>(null)

  useEffect(() => {
    if (textareaRef.current && !editorRef.current) {
      editorRef.current = CodeMirror.fromTextArea(textareaRef.current, {
        mode: 'javascript',
        theme: isDark ? 'darcula' : 'xq-light',
        lineNumbers: true,
      })
      editorRef.current.setValue(formCustomConfig)
      
      editorRef.current.on('change', () => {
        // we can keep it uncontrolled and save only on button click
      })
    }
    
    return () => {
      // cleanup if needed
    }
  }, [isDark])

  const handleSave = () => {
    if (editorRef.current) {
      const code = editorRef.current.getValue()
      setFormCustomConfig(code)
      toast.success('保存成功')
    }
  }

  return (
    <div className="space-y-4">
      <div className="h-60 border">
        <textarea
          ref={textareaRef}
          placeholder="Your custom code here."
          defaultValue={formCustomConfig}
        />
      </div>
      <Button
        variant="link"
        className="p-0"
        asChild
      >
        <a href="https://github.com/doocs/md#自定义上传逻辑" target="_blank" rel="noreferrer">
          参数详情
        </a>
      </Button>
      <Button className="block w-full" onClick={handleSave}>
        保存配置
      </Button>
    </div>
  )
}

// doocs-md-old/src/components/CustomUploadForm.vue
<script setup lang='ts'>
import { useStore } from '@/stores'
import { removeLeft } from '@/utils'
import CodeMirror from 'codemirror'

const store = useStore()

const code = useLocalStorage(`formCustomConfig`, removeLeft(`
  const {file, util, okCb, errCb} = CUSTOM_ARG
  const param = new FormData()
  param.append('file', file)
  util.axios.post('${window.location.origin}/upload', param, {
    headers: { 'Content-Type': 'multipart/form-data' }
  }).then(res => {
    okCb(res.url)
  }).catch(err => {
    errCb(err)
  })
`).trim())

const formCustomTextarea = useTemplateRef<HTMLTextAreaElement>(`formCustomTextarea`)

const editor = ref< CodeMirror.EditorFromTextArea | null>(null)

onMounted(() => {
  editor.value = markRaw(CodeMirror.fromTextArea(formCustomTextarea.value!, {
    mode: `javascript`,
    theme: store.isDark ? `darcula` : `xq-light`,
    lineNumbers: true,
  }))

  // 嵌套使用 nextTick 才能确保生效，具体原因未知
  nextTick(() => {
    nextTick(() => {
      editor.value?.setValue(code.value)
    })
  })
})

function formCustomSave() {
  const str = editor.value!.getValue()
  if (!str.trim()) {
    toast.error(`自定义代码不能为空`)
    return
  }
  localStorage.setItem(`formCustomConfig`, str)
  toast.success(`保存成功`)
}
</script>

<template>
  <div class="space-y-4">
    <div class="h-60 border">
      <textarea
        ref="formCustomTextarea"
        placeholder="Your custom code here."
      />
    </div>
    <Button
      variant="link"
      class="p-0"
      href="https://github.com/doocs/md#自定义上传逻辑"
      target="_blank"
    >
      参数详情
    </Button>
    <Button class="block" @click="formCustomSave">
      保存配置
    </Button>
  </div>
</template>
