// doocs-md-new/src/components/PostInfo.tsx
import { useEffect, useState, useMemo } from 'react'
import type { Post, PostAccount } from '@/types'
import { useStore } from '@/stores'
import { Info } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter, DialogTrigger } from '@/components/ui/dialog'
import { PostTaskDialog } from './PostTaskDialog'

export function PostInfo() {
  const { output, editor } = useStore()

  const [dialogVisible, setDialogVisible] = useState(false)
  const [extensionInstalled, setExtensionInstalled] = useState(false)
  const [allAccounts, setAllAccounts] = useState<PostAccount[]>([])
  const [postTaskDialogVisible, setPostTaskDialogVisible] = useState(false)

  const [form, setForm] = useState<Post>({
    title: '',
    desc: '',
    thumb: '',
    content: '',
    markdown: '',
    accounts: [] as PostAccount[],
  })

  const allowPost = useMemo(() => {
    return extensionInstalled && form.accounts.some((a) => a.checked)
  }, [extensionInstalled, form.accounts])

  const fetchAccounts = async () => {
    return new Promise<void>((resolve) => {
      if (typeof window !== 'undefined' && (window as any).$syncer) {
        (window as any).$syncer.getAccounts((resp: PostAccount[]) => {
          setAllAccounts(resp.map((a) => ({ ...a, checked: true })))
          resolve()
        })
      } else {
        resolve()
      }
    })
  }

  const checkExtension = () => {
    if (typeof window !== 'undefined' && (window as any).$syncer !== undefined) {
      setExtensionInstalled(true)
      return
    }

    let count = 0
    const timer = setInterval(async () => {
      if (typeof window !== 'undefined' && (window as any).$syncer !== undefined) {
        setExtensionInstalled(true)
        await fetchAccounts()
        clearInterval(timer)
        return
      }

      count++
      if (count > 10) {
        clearInterval(timer)
      }
    }, 500)
  }

  useEffect(() => {
    checkExtension()
  }, [])

  const prePost = async () => {
    let currentAccounts = allAccounts
    if (extensionInstalled && currentAccounts.length === 0) {
      const resp = await new Promise<PostAccount[]>((resolve) => {
        if (typeof window !== 'undefined' && (window as any).$syncer) {
          (window as any).$syncer.getAccounts((accountsResp: PostAccount[]) => {
            resolve(accountsResp.map((a) => ({ ...a, checked: true })))
          })
        } else {
          resolve([])
        }
      })
      currentAccounts = resp
      setAllAccounts(resp)
    }

    let auto: Post = {
      thumb: '',
      title: '',
      desc: '',
      content: '',
      markdown: '',
      accounts: [],
    }
    const accounts = currentAccounts.filter((a) => !['weixin', 'ipfs'].includes(a.type))
    try {
      const outputDiv = document.querySelector('#output')
      const img = outputDiv?.querySelector<HTMLImageElement>('img')
      
      let titleElement = null
      for (let i = 1; i <= 6; i++) {
        const h = outputDiv?.querySelector(`h${i}`)
        if (h) {
          titleElement = h
          break
        }
      }
      
      const p = outputDiv?.querySelector('p')

      auto = {
        thumb: img?.src ?? '',
        title: titleElement?.textContent ?? '',
        desc: p?.textContent ?? '',
        content: output,
        markdown: (editor as any)?.getValue() ?? '',
        accounts,
      }
    } catch (error) {
      console.log('error', error)
    } finally {
      setForm((prev) => ({
        ...prev,
        ...auto,
      }))
    }
  }

  const post = () => {
    setForm((prev) => ({
      ...prev,
      accounts: prev.accounts.filter((a) => a.checked),
    }))
    setPostTaskDialogVisible(true)
    setDialogVisible(false)
  }

  const handleAccountCheck = (uid: string, checked: boolean) => {
    setForm((prev) => ({
      ...prev,
      accounts: prev.accounts.map((a) => (a.uid === uid ? { ...a, checked } : a)),
    }))
  }

  return (
    <>
      <Dialog open={dialogVisible} onOpenChange={setDialogVisible}>
        <DialogTrigger asChild>
          <Button variant="outline" onClick={prePost}>
            发布
          </Button>
        </DialogTrigger>
        <DialogContent className="sm:max-w-[500px]">
          <DialogHeader>
            <DialogTitle>发布</DialogTitle>
          </DialogHeader>

          <div className="bg-blue-50 text-blue-900 border border-blue-200 rounded-md p-4 flex gap-3 text-sm">
            <Info className="h-5 w-5 shrink-0 text-blue-600" />
            <div className="flex flex-col gap-1">
              <span className="font-semibold">提示</span>
              <span>此功能由第三方浏览器插件支持，本平台不保证安全性及同步准确度。</span>
            </div>
          </div>

          {!extensionInstalled && (
            <div className="bg-yellow-50 text-yellow-900 border border-yellow-200 rounded-md p-4 flex gap-3 text-sm mt-2">
              <Info className="h-5 w-5 shrink-0 text-yellow-600" />
              <div className="flex flex-col gap-1">
                <span className="font-semibold">未检测到插件</span>
                <span>
                  请安装{' '}
                  <a
                    className="text-blue-600 hover:underline"
                    href="https://www.wechatsync.com/?utm_source=syncicon#install"
                    target="_blank"
                    rel="noreferrer"
                  >
                    文章同步助手
                  </a>{' '}
                  插件
                </span>
              </div>
            </div>
          )}

          <div className="w-full flex items-center gap-4 mt-4">
            <Label htmlFor="thumb" className="w-10 text-end">
              封面
            </Label>
            <Input
              id="thumb"
              value={form.thumb}
              onChange={(e) => setForm({ ...form, thumb: e.target.value })}
              placeholder="自动提取第一张图"
            />
          </div>
          <div className="w-full flex items-center gap-4">
            <Label htmlFor="title" className="w-10 text-end">
              标题
            </Label>
            <Input
              id="title"
              value={form.title}
              onChange={(e) => setForm({ ...form, title: e.target.value })}
              placeholder="自动提取第一个标题"
            />
          </div>
          <div className="w-full flex items-start gap-4">
            <Label htmlFor="desc" className="w-10 text-end mt-2">
              描述
            </Label>
            <Textarea
              id="desc"
              value={form.desc}
              onChange={(e) => setForm({ ...form, desc: e.target.value })}
              placeholder="自动提取第一个段落"
            />
          </div>

          <div className="w-full flex items-start gap-4">
            <Label className="w-10 text-end mt-2">账号</Label>
            <div className="flex flex-1 flex-col gap-2 max-h-[200px] overflow-y-auto">
              {form.accounts.map((account) => (
                <div key={account.uid + account.displayName} className="flex items-center gap-2">
                  <label className="flex flex-row items-center gap-4 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={account.checked}
                      onChange={(e) => handleAccountCheck(account.uid, e.target.checked)}
                      className="h-4 w-4 rounded border-gray-300 text-primary focus:ring-primary"
                    />
                    <span className="flex items-center gap-2 text-sm">
                      {account.icon && (
                        <img src={account.icon} alt="" className="inline-block h-[20px] w-[20px]" />
                      )}
                      {account.title} - {account.displayName ?? account.home}
                    </span>
                  </label>
                </div>
              ))}
              {form.accounts.length === 0 && extensionInstalled && (
                <div className="text-sm text-gray-500 mt-2">暂无可用账号，请在插件中配置</div>
              )}
            </div>
          </div>

          <DialogFooter>
            <Button variant="outline" onClick={() => setDialogVisible(false)}>
              取 消
            </Button>
            <Button disabled={!allowPost} onClick={post}>
              确 定
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <PostTaskDialog
        open={postTaskDialogVisible}
        onOpenChange={setPostTaskDialogVisible}
        post={form}
      />
    </>
  )
}

// doocs-md-old/src/components/CodemirrorEditor/EditorHeader/PostInfo.vue
<script setup lang="ts">
import type { Post, PostAccount } from '@/types'
import { useStore } from '@/stores'
import { Check, Info } from 'lucide-vue-next'
import { CheckboxIndicator, CheckboxRoot, Primitive } from 'radix-vue'

const store = useStore()
const { output, editor } = storeToRefs(store)

const dialogVisible = ref(false)
const extensionInstalled = ref(false)
const allAccounts = ref<PostAccount[]>([])
const postTaskDialogVisible = ref(false)

const form = ref<Post>({
  title: ``,
  desc: ``,
  thumb: ``,
  content: ``,
  markdown: ``,
  accounts: [] as PostAccount[],
})

const allowPost = computed(() => extensionInstalled.value && form.value.accounts.some(a => a.checked))

async function prePost() {
  if (extensionInstalled.value && allAccounts.value.length === 0) {
    await getAccounts()
  }

  let auto: Post = {
    thumb: ``,
    title: ``,
    desc: ``,
    content: ``,
    markdown: ``,
    accounts: [],
  }
  const accounts = allAccounts.value.filter(a => ![`weixin`, `ipfs`].includes(a.type))
  try {
    auto = {
      thumb: document.querySelector<HTMLImageElement>(`#output img`)?.src ?? ``,
      title: [1, 2, 3, 4, 5, 6]
        .map(h => document.querySelector(`#output h${h}`)!)
        .filter(h => h)[0]
        ?.textContent ?? ``,
      desc: document.querySelector(`#output p`)?.textContent ?? ``,
      content: output.value,
      markdown: editor.value?.getValue() ?? ``,
      accounts,
    }
  }
  catch (error) {
    console.log(`error`, error)
  }
  finally {
    form.value = {
      ...auto,
    }
  }
}

declare global {
  interface Window {
    syncPost: (data: { thumb: string, title: string, desc: string, content: string }) => void
    $syncer: any
  }
}

async function getAccounts(): Promise<void> {
  return new Promise((resolve) => {
    window.$syncer?.getAccounts((resp: PostAccount[]) => {
      allAccounts.value = resp.map(a => ({ ...a, checked: true }))
      resolve()
    })
  })
}

function post() {
  form.value.accounts = form.value.accounts.filter(a => a.checked)
  postTaskDialogVisible.value = true
  dialogVisible.value = false
}

function onUpdate(val: boolean) {
  if (!val) {
    dialogVisible.value = false
  }
}

function checkExtension() {
  if (window.$syncer !== undefined) {
    extensionInstalled.value = true
    return
  }

  // 如果插件还没加载，5秒内每 500ms 检查一次
  let count = 0
  const timer = setInterval(async () => {
    if (window.$syncer !== undefined) {
      extensionInstalled.value = true
      await getAccounts()
      clearInterval(timer)
      return
    }

    count++
    if (count > 10) { // 5秒后还是没有检测到，就停止检查
      clearInterval(timer)
    }
  }, 500)
}

onBeforeMount(() => {
  checkExtension()
})
</script>

<template>
  <Dialog v-model:open="dialogVisible" @update:open="onUpdate">
    <DialogTrigger>
      <Button variant="outline" @click="prePost">
        发布
      </Button>
    </DialogTrigger>
    <DialogContent>
      <DialogHeader>
        <DialogTitle>发布</DialogTitle>
      </DialogHeader>
      <Alert>
        <Info class="h-4 w-4" />
        <AlertTitle>提示</AlertTitle>
        <AlertDescription>
          此功能由第三方浏览器插件支持，本平台不保证安全性及同步准确度。
        </AlertDescription>
      </Alert>

      <Alert v-if="!extensionInstalled">
        <Info class="h-4 w-4" />
        <AlertTitle>未检测到插件</AlertTitle>
        <AlertDescription>
          请安装
          <Primitive
            as="a" class="text-blue-500" href="https://www.wechatsync.com/?utm_source=syncicon#install"
            target="_blank"
          >
            文章同步助手
          </Primitive>
          插件
        </AlertDescription>
      </Alert>

      <div class="w-full flex items-center gap-4">
        <Label for="thumb" class="w-10 text-end">
          封面
        </Label>
        <Input id="thumb" v-model="form.thumb" placeholder="自动提取第一张图" />
      </div>
      <div class="w-full flex items-center gap-4">
        <Label for="title" class="w-10 text-end">
          标题
        </Label>
        <Input id="title" v-model="form.title" placeholder="自动提取第一个标题" />
      </div>
      <div class="w-full flex items-start gap-4">
        <Label for="desc" class="w-10 text-end">
          描述
        </Label>
        <Textarea id="desc" v-model="form.desc" placeholder="自动提取第一个段落" />
      </div>

      <div class="w-full flex items-start gap-4">
        <Label class="w-10 text-end">
          账号
        </Label>
        <div class="flex flex-1 flex-col gap-2">
          <div v-for="account in form.accounts" :key="account.uid + account.displayName" class="flex items-center gap-2">
            <label class="flex flex-row items-center gap-4">
              <CheckboxRoot
                v-model:checked="account.checked"
                class="bg-background hover:bg-muted h-[25px] w-[25px] flex appearance-none items-center justify-center border border-gray-200 rounded-[4px] outline-none"
              >
                <CheckboxIndicator>
                  <Check v-if="account.checked" class="h-4 w-4" />
                </CheckboxIndicator>
              </CheckboxRoot>
              <span class="flex items-center gap-2 text-sm">
                <img
                  :src="account.icon"
                  alt=""
                  class="inline-block h-[20px] w-[20px]"
                >
                {{ account.title }} - {{ account.displayName ?? account.home }}
              </span>
            </label>
          </div>
        </div>
      </div>

      <DialogFooter>
        <Button variant="outline" @click="dialogVisible = false">
          取 消
        </Button>
        <Button :disabled="!allowPost" @click="post">
          确 定
        </Button>
      </DialogFooter>
    </DialogContent>
  </Dialog>

  <PostTaskDialog v-model:open="postTaskDialogVisible" :post="form" />
</template>
